{% set name = "python-lsp-jsonrpc" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4688e453eef55cd952bff762c705cedefa12055c0aec17a06f595bcc002cc912

build:
  noarch: python
  number: 1
  script: python -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.2.0
    # Needed at build time to produce a package with the correct version for pip
    # See https://github.com/pypa/setuptools_scm/issues/636#issuecomment-1026435048
    - setuptools_scm >=3.4.3
  run:
    - python >={{ python_min }}
    - ujson >=3.0.0

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - pylsp_jsonrpc
    - pylsp_jsonrpc.dispatchers
  commands:
    - python -m pip check
    # The pip version can be reported incorrectly if setuptools_scm isn't available
    # at build time.
    # Based on https://github.com/conda-forge/pyusb-feedstock/pull/4
    - pip list | grep -i {{ name }} | grep {{ version }}

about:
  home: https://github.com/python-lsp/python-lsp-jsonrpc
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A Python 3.8+ server implementation of the JSON RPC 2.0 protocol.
  dev_url: https://github.com/python-lsp/python-lsp-jsonrpc

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
    - andfoy
    - steff456
